//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pocorall.SCM_Notifier.Properties {
    using System;
    using System.Windows.Forms;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pocorall.SCM_Notifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Errors {
            get {
                object obj = ResourceManager.GetObject("Errors", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        internal static System.Drawing.Bitmap getBitmap(string bitmapName) 
        {
            object obj = ResourceManager.GetObject(bitmapName, resourceCulture);
           return ((System.Drawing.Bitmap)(obj));
        }
        internal static void getBitmap(ImageList.ImageCollection images, string bitmapName)
        {
            System.Drawing.Bitmap bitmap = getBitmap(bitmapName);
            images.Add(bitmapName, bitmap);
        }
        
        internal static System.Drawing.Bitmap Toolbar_AddFile {
            get {
                object obj = ResourceManager.GetObject("Toolbar_AddFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_AddFolder {
            get {
                object obj = ResourceManager.GetObject("Toolbar_AddFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_Commit {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Commit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_OpenFolder {
            get {
                object obj = ResourceManager.GetObject("Toolbar_OpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_Remove {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ShowChangeLogs {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ShowChangeLogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_ShowLogs {
            get {
                object obj = ResourceManager.GetObject("Toolbar_ShowLogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_Update {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayIcon_Error {
            get {
                object obj = ResourceManager.GetObject("TrayIcon_Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayIcon_NeedUpdate {
            get {
                object obj = ResourceManager.GetObject("TrayIcon_NeedUpdate", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayIcon_Unknown {
            get {
                object obj = ResourceManager.GetObject("TrayIcon_Unknown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon TrayIcon_UpToDate {
            get {
                object obj = ResourceManager.GetObject("TrayIcon_UpToDate", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
